### ISSUE TITLE
Compiling Error 

### ISSUE THREAD

**Issue by aleemladha** [am0nsec/SharpHellsGate#3]
Using vs 2017 , .net framework 4.8 , language version 7.3

Getting this error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Span<>' could not be found (are you missing a using directive or an assembly reference?)	\SharpHellsGate-master\SharpHellsGate\Module\MemoryUtil.cs	32	Active

**Comment by am0nsec** [comment]
You are trying to compile .NET Core 5.0 code via .NET Framework. There is no such thing like `Span` in .net Framework.

You can download .NET Core 5.0 here: https://dotnet.microsoft.com/download/dotnet/5.0
You can download Visual Studio 2019 Preview here: https://visualstudio.microsoft.com/vs/preview/

I will try to modify the code to have something that work with both .NET Core and .NET Framework. Cannot promise anything though.

**Comment by aleemladha** [comment]
I had to enable this. It's working 

![image](https://user-images.githubusercontent.com/26311391/84693490-3b93ae00-af50-11ea-99ca-785020178c95.png)
